#ifndef UC_DEFS_HPP_c49e54971d13f14fbc634d7a0fe4b38d421279e7
#define UC_DEFS_HPP_c49e54971d13f14fbc634d7a0fe4b38d421279e7

/**
 * defs.hpp
 *
 * This file provides macro definitions that are used in other library
 * code files, as well as in code generated by the uC compiler.
 *
 * Names are mangled to avoid clashing with C++ names.
 *
 * Project UID c49e54971d13f14fbc634d7a0fe4b38d421279e7
 */

// Basic concatenation macro
#define UC_CONCAT_(a, b) a ## b
#define UC_CONCAT(a, b) UC_CONCAT_(a, b)

// Prepend prefix to names generated through macros
#define UC_PREFIX(item) UC_CONCAT(ucp_, item)

// A primitive type of the given name
#define UC_PRIMITIVE(name)                     \
  UC_PREFIX(UC_CONCAT(p_, name))

// A raw user-defined type of the given name, used in type definitions
#define UC_TYPEDEF(name)                       \
  UC_PREFIX(UC_CONCAT(t_, name))

// A user-defined type wrapped in a reference
#define UC_REFERENCE(name)                     \
  uc_reference<UC_PREFIX(UC_CONCAT(t_, name))>

// An array type with the given element type
#define UC_ARRAY(elem_type)                    \
  UC_PREFIX(array<elem_type>)

// A function of the given name
#define UC_FUNCTION(name)                      \
  UC_PREFIX(UC_CONCAT(f_, name))

// A variable of the given name
#define UC_VAR(name)                           \
  UC_PREFIX(UC_CONCAT(v_, name))

#endif // UC_DEFS_HPP_c49e54971d13f14fbc634d7a0fe4b38d421279e7
